import { tailwindStrictConfig } from "./tailwind.config-strict.ts";

/** @type {import('tailwindcss').Config} */
export default {
  ...tailwindStrictConfig,
  corePlugins: [
    // "display",
    // typography
    "fontVariantNumeric",
    "textColor",
    "fontFamily",
    "fontSize",
    "fontWeight",
    "fontStyle",
    "textAlign",
    "textDecoration",
    // sizing
    "width",
    "height",
    "maxWidth",
    "minWidth",
    "maxHeight",
    "minHeight",
    "margin",
    "padding",
    "boxSizing",
    // outline
    "outlineWidth",
    "outlineColor",
    "outlineOffset",
    "outlineStyle",
    // misc
    "opacity",
    "objectFit",
    "objectPosition",
    "overflow",
    "lineHeight",
    "backgroundColor",
    "backgroundSize",
    "backgroundImage",
    "backgroundPosition",
    // "borderColor",
    // "borderCollapse",
    // "borderWidth",
    // "borderStyle",
    // "borderSpacing",
    // // "borderOpacity",
    "clear",
    "textWrap",
    "wordBreak",
    // "hyphens",
    // "space",
    "listStyleImage",
    "listStylePosition",
    "listStyleType",
    "verticalAlign",
  ],
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
};
